// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wiqxnoqemahqbvwhxaku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpcXhub3FlbWFocWJ2d2h4YWt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MDU4NDUsImV4cCI6MjA2MTk4MTg0NX0.e1LbzJI5VJXQatKP5rvVwDr8glY8C5vs7nJszAvKTOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);